version: "3.9"
services:
  ftp:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-docker
    expose:
      - "3000"
    volumes:
      - ./files:/files
      - ./output:/output
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ftp
    ports:
      - "4000:4000"
